name: First GHA

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Greeting
      run: echo "Hello world! I'm learning Github Actions"
